name: Publish package to GitHub Packages
on:
  push:
    branches:
      - alvearie-develop
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Publish package
        run: Src/java/./gradlew -b Src/java/build.gradle clean build jar publishAllPublicationsToGitHubPackagesRepository
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

